version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: bee_app
    volumes:
      - ..:/workspaces/Bee
    working_dir: /workspaces/Bee
    env_file:
      - ../.env
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: python main.py

  db:
    image: postgres:latest
    container_name: bee_db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./doc.env
    # environment:
    #   POSTGRES_USER: ${PG_USER}
    #   POSTGRES_DB: ${PG_NAME}
    #   POSTGRES_PASSWORD: ${PG_PASSWORD}
    #   POSTGRES_HOST: ${PG_HOST}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../schema_pg.sql:/docker-entrypoint-initdb.d/schema_pg.sql

volumes:
  postgres-data:
